/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabasePublishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!supabaseUrl || !supabasePublishableKey) {
	throw new Error("Missing Supabase configuration. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.");
}

export const projectId = supabaseUrl.replace("https://", "").replace(".supabase.co", "");
export const publicAnonKey = supabasePublishableKey;