/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "https://oqyrsidgokvryizwikna.supabase.co";
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xeXJzaWRnb2t2cnlpendpa25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI5ODEzMTQsImV4cCI6MjA5ODU1NzMxNH0.g0w1UxIQaMe8kp0OS66uwjxLzzda16-ZlcVsC5bY9OM";

export const projectId = supabaseUrl.replace("https://", "").replace(".supabase.co", "");
export const publicAnonKey = supabaseAnonKey;